### PR TITLE
test: Set-up integration test [PAGOPA-786]

### PR DESCRIPTION
**Pull request by cap-ang**
#### List of Changes

- GitHub Actions pipelines added
- `.identity` added
- docker `HOST_PORT` updated
- check health logic in `run_docker.sh` changed

#### How Has This Been Tested?

It has been tested via smoke test and integration test pipelines interacting with resources in `dev` environment

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cap-ang** [comment]
update_code

**Comment by jacopocarlini** [comment]
update_code

**Comment by cap-ang** [comment]
update_code

**Review by jacopocarlini — APPROVED** [review]
good job!

**Pull request merged**
